services:
  - type: web
    name: arenapass-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Secret
        sync: false
      - key: Jwt__Issuer
        value: ArenaPass
      - key: Jwt__Audience
        value: ArenaPass
      - key: Jwt__ExpiraEmMinutos
        value: "480"
      - key: Cors__FrontendOrigins__0
        sync: false
      - key: Pix__Chave
        sync: false
      - key: Pix__NomeRecebedor
        value: ArenaPass
      - key: Pix__Cidade
        value: SAO PAULO
