// <auto-generated />
using System;
using ArenaPass.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArenaPass.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ArenaPassDbContext))]
    partial class ArenaPassDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArenaPass.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("EspacoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuadraId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TaxaValor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EspacoId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("QuadraId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Convite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("AlunoCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("AlunoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Convites");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Espaco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DominioPersonalizado")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DominioPersonalizado")
                        .IsUnique();

                    b.HasIndex("Subdominio")
                        .IsUnique();

                    b.ToTable("Espacos");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Modalidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EspacoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EspacoId", "Nome")
                        .IsUnique();

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.ProfessorEspaco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EspacoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatusAprovacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EspacoId");

                    b.HasIndex("ProfessorId", "EspacoId")
                        .IsUnique();

                    b.ToTable("ProfessoresEspacos");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Quadra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracaoSlotMinutos")
                        .HasColumnType("integer");

                    b.Property<Guid>("EspacoId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("HoraAbertura")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraFechamento")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ModalidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TaxaPorHora")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EspacoId");

                    b.HasIndex("ModalidadeId");

                    b.ToTable("Quadras");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.SolicitacaoRegistroProfessor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EspacoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EspacoId", "Email")
                        .IsUnique();

                    b.ToTable("SolicitacoesRegistroProfessor");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("EspacoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EspacoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("ArenaPass.Domain.Entities.Espaco", "Espaco")
                        .WithMany()
                        .HasForeignKey("EspacoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaPass.Domain.Entities.Professor", "Professor")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaPass.Domain.Entities.Quadra", "Quadra")
                        .WithMany("Agendamentos")
                        .HasForeignKey("QuadraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Espaco");

                    b.Navigation("Professor");

                    b.Navigation("Quadra");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Convite", b =>
                {
                    b.HasOne("ArenaPass.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany("Convites")
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Modalidade", b =>
                {
                    b.HasOne("ArenaPass.Domain.Entities.Espaco", "Espaco")
                        .WithMany("Modalidades")
                        .HasForeignKey("EspacoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Espaco");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Professor", b =>
                {
                    b.HasOne("ArenaPass.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Professor")
                        .HasForeignKey("ArenaPass.Domain.Entities.Professor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.ProfessorEspaco", b =>
                {
                    b.HasOne("ArenaPass.Domain.Entities.Espaco", "Espaco")
                        .WithMany()
                        .HasForeignKey("EspacoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaPass.Domain.Entities.Professor", "Professor")
                        .WithMany("Espacos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espaco");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Quadra", b =>
                {
                    b.HasOne("ArenaPass.Domain.Entities.Espaco", "Espaco")
                        .WithMany("Quadras")
                        .HasForeignKey("EspacoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaPass.Domain.Entities.Modalidade", "Modalidade")
                        .WithMany("Quadras")
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Espaco");

                    b.Navigation("Modalidade");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.SolicitacaoRegistroProfessor", b =>
                {
                    b.HasOne("ArenaPass.Domain.Entities.Espaco", "Espaco")
                        .WithMany()
                        .HasForeignKey("EspacoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Espaco");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ArenaPass.Domain.Entities.Espaco", "Espaco")
                        .WithMany()
                        .HasForeignKey("EspacoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Espaco");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Agendamento", b =>
                {
                    b.Navigation("Convites");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Espaco", b =>
                {
                    b.Navigation("Modalidades");

                    b.Navigation("Quadras");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Modalidade", b =>
                {
                    b.Navigation("Quadras");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Professor", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Espacos");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Quadra", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("ArenaPass.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Professor");
                });
#pragma warning restore 612, 618
        }
    }
}
